sudo: false
language: python
python:
  - 2.7
  - 3.7

install: pip install -U tox-travis tox-pipenv pip setuptools
script: tox

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      python: 3.7
      script: tox -e flake8
